services:


  database:
    image: mysql:8
    container_name: database
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: backend
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./volumes/mysql-data:/var/lib/mysql #내가 지정한 경로
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD']
      timeout: 20s
      retries: 10


  backend1:  # 서비스 이름은 컨테이너간 통신하기 위한 이름
    image: backend
    container_name: backend1
    environment:
      PROJECT_NAME: 백앤드 서버1
    depends_on:
      database:
        condition: service_healthy
      
  backend2:  # 서비스 이름은 컨테이너간 통신하기 위한 이름
    image: backend
    container_name: backend2
    environment:
      PROJECT_NAME: 백앤드 서버2
    depends_on:
      database:
        condition: service_healthy
      
  backend3:  # 서비스 이름은 컨테이너간 통신하기 위한 이름
    image: backend
    container_name: backend3
    environment:
      PROJECT_NAME: 백앤드 서버3
    depends_on:
      database:
        condition: service_healthy
      
  nginx:
    image: nginx:1.25
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
      - backend3