
pipeline {
    agent any

    environment {
        PROJECT_DIR = '/var/jenkins_home/workspace/backend5/backendProject'   // 백앤드 서버 프로젝트 폴더
        COMPOSE_FILE = 'docker-compose.backend.yml'

    }

    stages {

          stage('Cleanup Containers') {
            steps {
                dir("${PROJECT_DIR}") {
                    sh "docker-compose -f ${COMPOSE_FILE} down"
                }
             }
          }


        stage('Build') {
          steps {
            dir("${PROJECT_DIR}") {
              sh 'chmod +x gradlew'
              sh './gradlew clean build'
            }
          }
        }


        stage('Compose Up') {
          steps {
            dir("${PROJECT_DIR}") {
              sh "docker-compose -f ${COMPOSE_FILE} up -d --build"
            }
          }
        }

        stage('Restart Nginx') {
          steps {
            sh 'docker restart nginx || true'
          }
        }

      }
}
